name: Github Pages Deploy
on:
  push:
    branches:
      - "master"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Deploy :rocket:
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages